### ISSUE TITLE
Could you add more details how to debug go compiler

### ISSUE THREAD

**Issue by valery-barysok** [artspb/blog#1]
It will be great to describe all steps how to prepare go source code for debug.

Currently It is not obvious from your post.

I am getting errors when try to run `go build` from source code:

> main.go:19:2: use of internal package not allowed

**Comment by artspb** [comment]
@valery-barysok It seems one important step is missing, indeed. Does it help if you configure `GOROOT` to `devel` as described in [this article](https://www.jetbrains.com/help/go/how-to-use-goland-to-contribute-to-go.html)?

**Comment by valery-barysok** [comment]
@artspb, It works now. Thank you.

**Comment by artspb** [comment]
Thank you for reporting!
